name: phones_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stacked_services: ^1.6.0
  stacked: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  stacked_generator: ^1.6.1


flutter:

  uses-material-design: true

  assets:
    - asset/images/
    